### ISSUE TITLE
Update league/flysystem dependencies

### ISSUE THREAD

**Issue by kokomomtl** [SimpleSoftwareIO/simple-sqs-extended-client#4]
Hi, I am unable to install the client because the dependencies are too old and conflict with my other packages. Are you planning on updating the dependencies soon? Thank-you

**Comment by SimplyCorey** [comment]
Not sure what is wrong, but we use ^3 which includes the latest.

**Comment by lfabordeos-fastfwd** [comment]
For anyone that gets here, I believe the issue lies with the installation instructions that's stuck to v1 of the library. Use `~2` for newer laravel applications.
