### ISSUE TITLE
Call to undefined method SimpleSoftwareIO\SqsDisk\SqsDiskQueue::readyNow()

### ISSUE THREAD

**Issue by martin-ro** [SimpleSoftwareIO/simple-sqs-extended-client#8]
When using the package with Horizon I'm getting these errors:

```
Call to undefined method SimpleSoftwareIO\SqsDisk\SqsDiskQueue::readyNow()
```

Is the package not intended to be used with Horizon or is this a bug?

Cheers

**Comment by SimplyCorey** [comment]
Horizon only works with the Redis driver as far as I know. Are you using SQS with horizon?

From the docs: 
Laravel Horizon provides a beautiful dashboard and code-driven configuration for your Laravel powered Redis queues. Horizon allows you to easily monitor key metrics of your queue system such as job throughput, runtime, and job failures.
